import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {default:"Fluxon - The Minimal PDF Manipulator"},
  description: "Generated by create next app",
  icons : {
    icon: '/icons/real_icon.png'
  },
  keywords: ["pdf tools", "pdf editor", "fluxon", "merge pdf", "split pdf"],
  authors: [{ name: "The Caax" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster position="top-right" closeButton="true" richColors="true" theme="dark" />
        {children}
      </body>
    </html>
  );
}
