import { Toaster } from "sonner";
import "../styles/globals.css";

export const metadata = {
  title: {default:"Fluxon - The Minimal PDF Manipulator"},
  description: "Generated by create next app",
  icons : {
    icon: '/icons/real_icon.png'
  },
  keywords: ["pdf tools", "pdf editor", "fluxon", "merge pdf", "split pdf"],
  authors: [{ name: "The Caax" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" closeButton="true" richColors="true" theme="dark" />
        {children}
      </body>
    </html>
  );
}
